import {
  dp,
  thirteen,
  fourteen,
  fifteen,
  sixteen,
  seventeen,
  eighteen,
  nineteen,
  twenty,
  twentyone,
  twentytwo,
  twentythree,
} from "./product-images";

// featuredProducts and all products data
import {
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
} from "./product-images";

// ShopCategory Image
import {
  twentyfour,
  twentyfive,
  twentysix,
  twentyseven,
  twentyeight,
  twentynine,
  thirty,
  thirtyone,
  thirtytwo,
  thirtythree,
} from "./product-images";

// product4
import { thirtyfour, thirtyfive, thirtysix } from "./product-images";

export const featuredProducts = [
  {
    id: 1,
    name: "Generator",
    age: "1 year old",
    description: "2 days battery life, 100% durable",
    price: 20000,
    category: "Electronics",
    condition: "Used",
    image: one,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 2,
    name: "Drum Set",
    age: "Good as new",
    description: "Perfect sound, strong hardware",
    price: 150000,
    category: "Musical Instruments",
    condition: "Used",
    image: two,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 3,
    name: "Wrist Watch",
    age: "4 Months old",
    description: "Classic look, original strap",
    price: 23000,
    category: "Fashion",
    condition: "Used",
    image: three,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 4,
    name: "Chair",
    age: "1 year old",
    description: "Comfortable with wooden frame",
    price: 5000,
    category: "Furniture",
    condition: "Used",
    image: four,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 5,
    name: "Blender",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Kitchen",
    condition: "Used",
    image: five,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 6,
    name: "Gas Cylinder",
    age: "3 years old",
    description: "12kg, no leakage",
    price: 25000,
    category: "Home Appliance",
    condition: "Used",
    image: six,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 7,
    name: "Canon 4D",
    age: "4 years old",
    description: "Pro camera for photography",
    price: 600000,
    category: "Cameras",
    condition: "Used",
    image: seven,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 8,
    name: "Tripod Stand",
    age: "2 years old",
    description: "Adjustable, sturdy stand",
    price: 15000,
    category: "Accessories",
    condition: "Used",
    image: eight,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 9,
    name: "Samsung Laptop",
    age: "10 Months old",
    description: "Fast and reliable for office work",
    price: 230000,
    category: "Computers",
    condition: "Used",
    image: nine,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 10,
    name: "PS 4 Console",
    age: "1 Year old",
    description: "Fully working, comes with controller",
    price: 630000,
    category: "Gaming",
    condition: "Used",
    image: ten,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
];

export const ShopCategoryData = [
  {
    id: 1,
    category: "Washing Machine",
    image: twentyfour,
  },
  {
    id: 2,
    category: "Bag",
    image: twentyfive,
  },
  {
    id: 3,
    category: "Fans",
    image: twentysix,
  },
  {
    id: 4,
    category: "Stove/Cooker",
    image: twentyseven,
  },
  {
    id: 5,
    category: "Laptops",
    image: twentyeight,
  },
  {
    id: 6,
    category: "Phones",
    image: twentynine,
  },
  {
    id: 7,
    category: "Clothes",
    image: thirty,
  },
  {
    id: 8,
    category: "Shoes",
    image: thirtyone,
  },
  {
    id: 9,
    category: "Kitchen Items",
    image: thirtytwo,
  },
  {
    id: 10,
    category: "Games",
    image: thirtythree,
  },
];

export const product4Data = [
  {
    id: 1,
    name: "Next Level Style",
    image: thirtyfour,
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. molestias corrupti doloribus umquam.",
    bg: 'var(--product)'
  },
   {
    id: 2,
    name: "Superb Home Theater",
    image: thirtyfive,
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. molestias corrupti doloribus umquam.",
    bg: 'var(--header-color)'
  },
   {
    id: 3,
    name: "Beauty Hair Dryer",
    image: thirtysix,
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. molestias corrupti doloribus umquam.",
    bg: 'var(--product)'
  },
];

// All products data
export const products = [
  {
    id: 1,
    name: "Hp Laptop",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Laptops",
    condition: "Used",
    image: five,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 2,
    name: "Blender",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Kitchen",
    condition: "Used",
    image: seventeen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 3,
    name: "Redmi 10",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Phones",
    condition: "Used",
    image: six,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 4,
    name: "Washing Machine",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Washing Machine",
    condition: "Used",
    image: one,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 5,
    name: "Coffee maker",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Kitchen",
    condition: "Used",
    image: nine,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 6,
    name: "Tripod Stand",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Aplliances",
    condition: "Used",
    image: twenty,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 6,
    name: "PS5 console",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Games",
    condition: "Used",
    image: ten,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 7,
    name: "Drums",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Instrument",
    condition: "Used",
    image: fourteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 8,
    name: "Home Theatre",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Appliances",
    condition: "Used",
    image: thirtyfive,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 9,
    name: "Shirt",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Fashion",
    condition: "Used",
    image: seven,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 10,
    name: "Shoes",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Shoes",
    condition: "Used",
    image: eight,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 11,
    name: "Gas Cylinder",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Kitchen",
    condition: "Used",
    image: eighteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 12,
    name: "Hand Bag",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Fashion",
    condition: "Used",
    image: two,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 13,
    name: "Generator",
    age: "1 year old",
    description: "2 days battery life, 100% durable",
    price: 20000,
    category: "Electronics",
    condition: "Used",
    image: thirteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 14,
    name: "Smart Watch",
    age: "Good as new",
    description: "Perfect sound, strong hardware",
    price: 150000,
    category: "Wrist Watch",
    condition: "Used",
    image: thirtyfour,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 15,
    name: "Samsung A3",
    age: "4 Months old",
    description: "Classic look, original strap",
    price: 23000,
    category: "Phones",
    condition: "Used",
    image: twentyone,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 16,
    name: "Chair",
    age: "1 year old",
    description: "Comfortable with wooden frame",
    price: 5000,
    category: "Furniture",
    condition: "Used",
    image: sixteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 17,
    name: "Hair Blower",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Aplliances",
    condition: "Used",
    image: thirtysix,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 18,
    name: "Wrist Watch",
    age: "3 years old",
    description: "12kg, no leakage",
    price: 25000,
    category: "Wrist Watch",
    condition: "Used",
    image: fifteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 19,
    name: "Canon 4D",
    age: "4 years old",
    description: "Pro camera for photography",
    price: 600000,
    category: "Cameras",
    condition: "Used",
    image: nineteen,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 20,
    name: "Gas Burner",
    age: "2 years old",
    description: "Adjustable, sturdy stand",
    price: 15000,
    category: "Kitchen",
    condition: "Used",
    image: four,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 21,
    name: "Samsung Laptop",
    age: "10 Months old",
    description: "Fast and reliable for office work",
    price: 230000,
    category: "Computers",
    condition: "Used",
    image: twentythree,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  {
    id: 22,
    name: "Fan",
    age: "1 Year old",
    description: "Fully working, comes with controller",
    price: 630000,
    category: "Appliances",
    condition: "Used",
    image: three,
    Location: "Enugu",
    seller: "John Doe",
    dp: dp,
  },
  // {
  //   id: 22,
  //   name: "Fan",
  //   age: "1 Year old",
  //   description: "Fully working, comes with controller",
  //   price: 630000,
  //   category: "Appliances",
  //   condition: "Used",
  //   image: twentynine,
  //   Location: "Enugu",
  //   seller: "John Doe",
  //   dp: dp,
  // },
];
