import {
  thirteen,
  fourteen,
  fifteen,
  sixteen,
  seventeen,
  eighteen,
  nineteen,
  twenty,
  twentyone,
  twentytwo,
  twentythree,
} from "./product-images";

export const products = [
  {
    id: 1,
    name: "Generator",
    age: "1 year old",
    description: "2 days battery life, 100% durable",
    price: 20000,
    category: "Electronics",
    condition: "Used",
    image: thirteen,
  },
  {
    id: 2,
    name: "Drum Set",
    age: "Good as new",
    description: "Perfect sound, strong hardware",
    price: 150000,
    category: "Musical Instruments",
    condition: "Used",
    image: fourteen,
  },
  {
    id: 3,
    name: "Wrist Watch",
    age: "4 Months old",
    description: "Classic look, original strap",
    price: 23000,
    category: "Fashion",
    condition: "Used",
    image: fifteen,
  },
  {
    id: 4,
    name: "Chair",
    age: "1 year old",
    description: "Comfortable with wooden frame",
    price: 5000,
    category: "Furniture",
    condition: "Used",
    image: sixteen,
  },
  {
    id: 5,
    name: "Blender",
    age: "Good as New",
    description: "Smooth blades, working fine",
    price: 10000,
    category: "Kitchen",
    condition: "Used",
    image: seventeen,
  },
  {
    id: 6,
    name: "Gas Cylinder",
    age: "3 years old",
    description: "12kg, no leakage",
    price: 25000,
    category: "Home Appliance",
    condition: "Used",
    image: eighteen,
  },
  {
    id: 7,
    name: "Canon 4D",
    age: "4 years old",
    description: "Pro camera for photography",
    price: 600000,
    category: "Cameras",
    condition: "Used",
    image: nineteen,
  },
  {
    id: 8,
    name: "Tripod Stand",
    age: "2 years old",
    description: "Adjustable, sturdy stand",
    price: 15000,
    category: "Accessories",
    condition: "Used",
    image: twenty,
  },
  {
    id: 9,
    name: "Samsung Laptop",
    age: "10 Months old",
    description: "Fast and reliable for office work",
    price: 230000,
    category: "Computers",
    condition: "Used",
    image: twentythree,
  },
  {
    id: 10,
    name: "PS 4 Console",
    age: "1 Year old",
    description: "Fully working, comes with controller",
    price: 630000,
    category: "Gaming",
    condition: "Used",
    image: twentytwo,
  },
];